# Generated by Django 5.2.7 on 2025-11-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_category_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
    ]
